id = "eclipsa"
name = "Eclipsa"
version = "0.1.0"
schema_version = 1
authors = ["rrenildopereiraa"]
description = "A variant of the Ariake Dark theme."
repository = "https://github.com/your-name/my-zed-extension"
